### ISSUE TITLE
MISSING CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by vanshikab52** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#10]
A Code_Of_Conduct.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions. It sets clear guidelines for expected behavior and helps ensure that all contributors feel safe and respected.
The repository currently lacks a CODE_OF_CONDUCT.md file which is an important resource for fostering a welcoming and inclusive environment within our community.
@Muskansahuincredible   You can assign this issue to me as I'm working under GSSoC'24 as a contributor. I can add a code of conduct to this project.
Thanks

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.
