### ISSUE TITLE
💡[FEATURE] Adding hover effects on the Log in and Sign up buttons in the navbar.

### ISSUE THREAD

**Issue by karishmaaa101** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#100]
### Description

On clicking the Log in and Sign up Buttons there is no color change, animation or hover effect present.
Most of the users who will come to the website will definitely go for the sign up /log in buttons first.
Therefore, adding some color change effects or a little hover animation would enhance user experience.

I am a Gssoc'24 contributor and I have followed all the guidelines for the same.

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/104766763/7e7aee25-268b-47ed-8ba9-470cf9d223da)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the StudyNotion-An-Online-Education-Platform. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by GovindSharma0708** [comment]
assign me this issue I would like to work on this issue of adding hover effect on login and signup button whenever user clicks on it.

**Comment by techmannih** [comment]
duplicate #98
