### ISSUE TITLE
Hover effect on social media logo

### ISSUE THREAD

**Issue by Shreyaa173** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#101]
### Description

Want to add hover effect on social media logos

### Screenshots

![Screenshot 2024-05-27 225817](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/144673309/7121cea5-5daf-4bbb-aee2-8ebf9ad9e4cb)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by GovindSharma0708** [comment]
I would like to work on this issue of hover effect on the Social Media logo please assign me this issue

**Comment by GovindSharma0708** [comment]
I have solved the issue and would like to contribute please assign it to me

**Comment by Shreyaa173** [comment]
I raised the issue and I have also done it. please assign me @Muskansahuincredible
