### ISSUE TITLE
BUG REPORT<In small size of mobile, some part of texts are not visible >

### ISSUE THREAD

**Issue by Poushmita** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#109]
### Description

The text - "Unlock the power of code" and the next line of this text is not visible in small size of mobile.it is a problem of responsiveness which we have to implement for better user experience.

### Screenshots

![studynotion](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/146666416/6bee2161-b66d-4c3c-942e-00ab97b78033)

### Additional information

It will improve the accessibility and user satisfaction. Ensuring text visibility on all devices is crucial for providing
seamless information to all users. 

### What browser are you seeing this bug on?

It has been observed on several popular mobile browsers, including Chrome
, Safari and Firefox. Ensuring compatibilty and readability across these browsers is essential for delivering a consistent user experience to all visitors.
### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Muskansahuincredible** [comment]
@Poushmita how u will make a change into this.

**Comment by Poushmita** [comment]
@Muskansahuincredible 


## Solution
 At First, I am going to put the heading `Unlock the Power of Code` in a separate div and will set the appropriate properties for it N.I.Z. dispaly:flex, flex-wrap:wrap etc.

If this worked then I will work for the below text as same.
