### ISSUE TITLE
BUG REPORT: Menu/Sidebar button not working

### ISSUE THREAD

**Issue by AnanyaJain25** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#110]
### Description

![Screenshot 2024-05-28 212035](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/136808696/300c8cca-f813-4a70-829f-0eabee86eac1)
this top right button is not working

### What browser are you seeing this bug on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Muskansahuincredible** [comment]
It's working
