### ISSUE TITLE
Bug: Only the headings are getting changed

### ISSUE THREAD

**Issue by urgetolearn** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#117]
### Description

When you click on free, new to coding, etc only the heading is getting changed but we need to change the description according to the heading for user enhancement. Please assign this task to me under GSSOC'24. I will get started immediately.

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/131844481/3e4bb53d-80c8-47c5-96b6-1edd19ebdf11)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by techmannih** [comment]
duplicate issue  #27
