### ISSUE TITLE
Navbar Not Sticky When Scrolling

### ISSUE THREAD

**Issue by shivamgaur99** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#12]
As the user scrolls down the page, the navbar should remain fixed at the top of the viewport. 
ensuring easy access to navigation links.

@Muskansahuincredible  Please assign it to me. Also, please add Labels 

here is a screenshot of this issue
![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/128178418/835d2bee-b807-4e34-bc5a-07f1128572c7)

**Comment by deepak9285** [comment]
hi @Muskansahuincredible  I am working on same type of personal project as an edtech platform i can contribute very much so can you please assign it to me for making navbar sticky. you can check by github profile

**Comment by shivamgaur99** [comment]
@deepak9285 i think issue should be assigned on a first-come, first-served basis

**Comment by shivamgaur99** [comment]
@Muskansahuincredible  now navbar is sticky
please assign so that i can make pull request
![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/128178418/5c017ebd-adff-4769-9d56-aa7933bfcb7d)

**Comment by Muskansahuincredible** [comment]
assigned @shivamgaur99

**Comment by Vaibhavs1612** [comment]
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.
