### ISSUE TITLE
💡[FEATURE] <To add hover effects for the login and signup button>

### ISSUE THREAD

**Issue by ayush-848** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#122]
### Description

I will add suitable hover effects for the login and signup button

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by techmannih** [comment]
duplicate
