### ISSUE TITLE
💡[FEATURE] <To add 'Contribute here' link in footer>

### ISSUE THREAD

**Issue by ayush-848** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#153]
### Description

I want to add 'Contribute here' link in footer under the 'Community' heading
on clicking it, user will be guided to this repo.

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/126975547/893bad5d-269a-4c92-acd9-57c5db53058b)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Samik123Mit** [comment]
pls, assign me the issue. I will make sure the task is done.
