### ISSUE TITLE
💡[FEATURE] Light/Dark toggle mode

### ISSUE THREAD

**Issue by harinisayani** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#154]
### Description

I observed that there is no light/dark toggle mode in web page.
I want to add it.
I am GSSOC'24 contributor.
Please assign me this task.

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by techmannih** [comment]
Duplicate
