### ISSUE TITLE
BUG REPORT <Profile image in testinomials is not visible>

### ISSUE THREAD

**Issue by Gamerking177** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#157]
### Description

Some profile image in review section is not visible

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/130808542/92f7ba1e-683f-4c48-a941-aea501713942)

### Additional information

Add images to it

### What browser are you seeing this bug on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by techmannih** [comment]
Problem in loading there is have images
