### ISSUE TITLE
📝[DOCS] Updating readme.md

### ISSUE THREAD

**Issue by Abhigna-arsam** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#160]
### Issue Description

i propose to add number of forks,pr opened ,pr closed,etc.

### Screenshots or Examples (if applicable)

![Screenshot 2024-06-03 113928](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/125258286/99d1938d-ae49-404d-b494-cac52078ae70)

as shown above

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines.
- [X] I have read the Code Of Conduct.
- [X] The changes doesn't break the code

**Comment by Abhigna-arsam** [comment]
@Muskansahuincredible @techmannih I'm GSSOC'24 contributer, please assign this issue to me

**Comment by Abhigna-arsam** [comment]
@Muskansahuincredible @techmannih I'm GSSOC'24 contributor,please give gssoc and level label.

**Comment by Samik123Mit** [comment]
pls, assign me the issue. I will make sure the task is done.

**Comment by 143divya** [comment]
Can you please assign me this issue for gssoc'24
