### ISSUE TITLE
[BUG] Favicon not visible

### ISSUE THREAD

**Issue by avanimathur** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#162]
### Description

A favicon has been added via the HTML file however it is not visible.
The path needs to be updated and the favicon image be saved with .ico extension

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/151984867/f438ce32-8d51-4f3b-a38f-38b58e184274)
Existing code - 
![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/151984867/8c9eca6a-853f-49ce-aa1f-87eda23e8212)

### Additional information

This is under GSSOC'24

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by techmannih** [comment]
No need
