### ISSUE TITLE
Spelling correction in Catalog drop-down menu

### ISSUE THREAD

**Issue by ankiiitagupta** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#169]
### What is your issue or question?

In catalog drop-down menu, development spelling is wrong.
Please assign this task to me under GSSOC'24. I can correct it.

![Screenshot 2024-06-03 211559](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/108889476/a17c4ece-31fb-4c60-9141-ec7cba39d6c2)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contribution Guidelines.
- [X] I have read the Code Of Conduct.
- [X] The changes don't break the code.

**Comment by techmannih** [comment]
Duplicate
