### ISSUE TITLE
BUG REPORT : Login page issue, and navbar hover

### ISSUE THREAD

**Issue by Sambit-Mondal** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#174]
### Description

- A white space is being left under the login section, which deteriorates the overall UI of the page.
- Also, I want to add hover effect to the navbar tabs

### Screenshots

https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/138088550/4bf34ea3-f5e3-4c0c-a792-e54cdbf75a8c

### What browser are you seeing this bug on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Samik123Mit** [comment]
pls, assign me the issue. I will make sure the task is done.
