### ISSUE TITLE
Adding social media links in footer section 

### ISSUE THREAD

**Issue by Braj-01** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#180]
### What is your issue or question?

There is no social media link in footer section and it must require for reaching out to connect with site.

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contribution Guidelines.
- [X] I have read the Code Of Conduct.
- [X] The changes don't break the code.

**Comment by Braj-01** [comment]
Please assign me this issue so that I can do task under GSSOC'24.

**Comment by Samik123Mit** [comment]
pls, assign me the issue. I will make sure the task is done.

**Comment by 143divya** [comment]
Can you please assign me this issue for gssoc'24

**Comment by techmannih** [comment]
Duplicate
