### ISSUE TITLE
 Mobile View Navbar Inoperable, Content Unreachable

### ISSUE THREAD

**Issue by shivamgaur99** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#19]
The navbar on our website fails to open on mobile devices, rendering the content within it inaccessible. This affects the user experience, preventing users from accessing essential navigation elements such as login, sign-in, home, and about us sections.

**Expected Behavior**
1. Navbar should expand on mobile devices.
2. All menu items should be accessible.

**Current Behavior**
1. Navbar remains unresponsive on mobile.
2. Content within the navbar is unreachable.

**Proposed Solution**
1. Investigate code for responsiveness.
2. Test on various mobile devices.
3. Optimize content for smaller screens.

screenshots :

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/128178418/81f388af-e9de-4e46-858a-e917650e32ec)

@Muskansahuincredible please assign it to me

**Comment by techmannih** [comment]
Thanks @shivamgaur99 for raising an issue
Okay assigned to you
