### ISSUE TITLE
WRONG TWITTER LOGO

### ISSUE THREAD

**Issue by sanskriti-lal** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#198]
### Description

Changing twitter's logo to "X"
I'm a GSSoC'24 contributor, well versed in web development. Can you please assign me this work @Muskansahuincredible 

### Screenshots

<img width="212" alt="Screenshot 2024-06-07 at 10 54 36 AM" src="https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/165655543/71d915f3-8960-4af4-8fa8-b76a4b9d0716">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by savvymonk05** [comment]
@Muskansahuincredible  please assign this issue to me

**Comment by techmannih** [comment]
Duplicate
