### ISSUE TITLE
Add Scroll-To-Top Button

### ISSUE THREAD

**Issue by MastanSayyad** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#20]
Implementing a Scroll-To-Top Button can provide a convenient way for users to quickly return to the top of the page.

Could you **please assign this issue to me under GSSoC'24?**

**Comment by techmannih** [comment]
explain expected behavior with Screenshot.

**Comment by MastanSayyad** [comment]
Yeah sure, @techmannih 
the expected behavior of the solution will look like this:

https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/101971980/99da723f-18c3-4fa6-93c5-c1ecdeb9008e

**Comment by MastanSayyad** [comment]
@techmannih, @Muskansahuincredible Please assign this issue

**Comment by MastanSayyad** [comment]
hey @techmannih please take a look at it and assign this issue to me as I've shown the expected behaviour of the feature which adds visually appealing view and can improve user experience.

**Comment by MastanSayyad** [comment]
thank you for assigning this to me @techmannih and I hope that you guys have solved your issue regarding repo.
