### ISSUE TITLE
Want to add issue template for this repo

### ISSUE THREAD

**Issue by AnitSarkar123** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#22]
Please assign me under GSSOC'24

**Comment by techmannih** [comment]
please clarify what do you want to solve and how to solve this issue also explain Issue template in detail with an example

**Comment by AnitSarkar123** [comment]
![Screenshot_20240515-173156~2.png](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/135215478/312806b9-61f9-4bdb-b9a0-42f191166ff5)

I can add all of these  temples in yml

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by suhanipaliwal** [comment]
If no one is working on this issue, I would like to work on this issue. Please assign it to me as the current assignee has already taken a lot of time.

**Comment by techmannih** [comment]
assigned @suhanipaliwal but need to same as screenshot template
