### ISSUE TITLE
Want to add a PR template for this repo

### ISSUE THREAD

**Issue by AnitSarkar123** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#23]
Please assign me under GSSOC'24

**Comment by techmannih** [comment]
please clarify what do you want and how to solve this this issue also explain PR template in detail with an example

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by techmannih** [comment]
assigned both @AnitSarkar123 and @suhanipaliwal who will first raise pr and first serve

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level as per gssoc guidelines on this issue.

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level as per gssoc guidelines on this issue.

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level as per gssoc guidelines on this issue.
