### ISSUE TITLE
💡[FEATURE] :Adding Instagram and LinkedIn accounts at footer

### ISSUE THREAD

**Issue by GAVINESHWAR** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#235]
### Description

In the Website at footer  section there is missing of Linked In and Instagram accounts Icon , I would like add those features to the website for better reach of contact details.

Assign me this issue @Muskansahuincredible  and @techmannih to make impact on the website 
Thank you 

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/124431955/210b3d86-08af-4080-b03d-734751049e6d)

Here there is missing Instagram and Linked in Icons 

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by GAVINESHWAR** [comment]
Assign me this issue @Muskansahuincredible  and @techmannih to make the contribution to this project

**Comment by jayanththalla** [comment]
please assign me @pa
i will hover with different colors

**Comment by minakshikr7** [comment]
I would like to work on this issue. Please assign this task to me under @GSSoC24
