### ISSUE TITLE
BUG REPORT:  - Hyphen  is added instead of Some name

### ISSUE THREAD

**Issue by GAVINESHWAR** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#236]
### Description

In the footer section and career topic **-** Hyphen is added instead of some kind name , allow me to remove that Hyphen and suggest me to added there specified name of topic 

Assign me this issue @Muskansahuincredible sir  to make it correct sir.
Thank you 

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/124431955/adc023ed-d2e1-4b64-804d-94d682224c35)

We can see Hyphen There 

### What browser are you seeing this bug on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by dhananjay6561** [comment]
@GAVINESHWAR Issue is solved. You may close it now.
