### ISSUE TITLE
💡[FEATURE] The Nav bar hover effect is missing 

### ISSUE THREAD

**Issue by SumithThota** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#249]
### Description

The Nav bar hover effect is missing it seems less interactive 
so let me fix the hover effect to the navbar as a gssoc24 contrributor

### Screenshots

check out this video:

https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/108344062/8974028b-ab82-4812-a4f5-d68eeb784957

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by minakshikr7** [comment]
I would like to work on this issue. Please assign this task to me under @GSSoC24
