### ISSUE TITLE
Make Navbar visible on top when start scolling down from anywhere in website

### ISSUE THREAD

**Issue by Utsavladia** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#251]
### Description

The navbar should be visible at top and if we want to hide it then it should be visible again when the user start to scroll down anywhere this will improve the user experience and make  website look great...

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/124615886/037c8be5-7594-4156-a9f6-97d78e10a259)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Anni299** [comment]
I'd like to work on this issue. Please assign it to me under GSSoC.

**Comment by Agarwalvidu** [comment]
Okay assigning this to you!

**Comment by Utsavladia** [comment]
@Agarwalvidu I opened this issue and wanted to work on it but didn't get any response...🙂

**Comment by Agarwalvidu** [comment]
So sorry for this @Utsavladia.
Actually I am new mentor for this, please look for more issues and tag me I will surely assign that one.

**Comment by Utsavladia** [comment]
@Agarwalvidu 
Okay...no issues
I have created new issue..
For this one the sticky navbar is not something for which i reaised this issue.... it was Flaoting navbar which will dissappear on scrolling done on home screen and will come back when start scrolling up.... I can provide the demo video if you want....

**Comment by Agarwalvidu** [comment]
Yes please do! @Utsavladia

**Comment by Utsavladia** [comment]
@Agarwalvidu 
It will be floating navbar like this which disappears and come back for better view of main screen
https://github.com/user-attachments/assets/918ed277-9620-408f-8487-72b0756944ff

**Comment by Agarwalvidu** [comment]
Umm I think we need it to be there when we scroll.
