### ISSUE TITLE
Fix "unloak potential section" for Mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#252]
### Description

The Unlock potentital section is not proper for teh mobile screen
It should be responsive to make the user experience best on all devices...

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/124615886/598fb158-382a-4a24-b9a5-bfe41489383f)

i would love to contribute to this project please assign this to me 

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Utsavladia** [comment]
@Agarwalvidu This is one of the issue that needed to be fixed and i would love to fix it under GSSOC

**Comment by Agarwalvidu** [comment]
Assigning!
