### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by suhanipaliwal** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#26]
I would like to add the code of conduct file which is necessary for every repository to have. Please assign this issue to me under GSSOC'24.

**Comment by shivamgaur99** [comment]
@suhanipaliwal 
already issue has been raised

**Comment by techmannih** [comment]
Hi @suhanipaliwal 
This is duplicate #10. I am closing this issue.
