### ISSUE TITLE
BUG REPORT<title> Add a counting animation to the 'About Us' page.

### ISSUE THREAD

**Issue by nikhildeshmukh170** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#265]
### Description

Add a counting animation to the 'About Us' page to display values when scrolling.

### Screenshots

![image](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/115735153/59247b02-ab3e-478b-8870-9a63bc4aefe3)

### Additional information

Benefits of the Correction:

- Enhances the professionalism of our website.

I am a GSSOC Contributor.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by nikhildeshmukh170** [comment]
@Muskansahuincredible, please assign this issue to me!

**Comment by Agarwalvidu** [comment]
Idea looks great. Go ahead!
@nikhildeshmukh170
