### ISSUE TITLE
BUG REPORT : Sticking Navbar!!

### ISSUE THREAD

**Issue by KomalMaurya** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#266]
### Description

Sticking Navbar to the top in every page so that user don't scroll up to find it out!!

Name : Komal Maurya
Role : Contributor in GSSoC'24
GitHub Profile Link : https://github.com/KomalMaurya

Please assign this issue to me under gssoc 2024!!

### Screenshots

![image](https://github.com/user-attachments/assets/f028b691-4654-44d5-bb0e-aa96f34e524a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Assigning it to you @KomalMaurya !
