### ISSUE TITLE
Hamburger menu icon is not working for the mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#275]
### Description

The menu is not working in mobile screen

### Screenshots

![image](https://github.com/user-attachments/assets/0045e30a-ad5f-4ffe-b2a9-38f34b2a3d46)

### Additional information

I would love to work on this under GSSOC

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
It is already assigned so closing this one.
