### ISSUE TITLE
BUG: Space over navbar

### ISSUE THREAD

**Issue by Jasleen1210** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#289]
### Description

![image](https://github.com/user-attachments/assets/2485f3fb-c8d5-434b-9372-cb62fecf646a)

The current page has a white portion above the navbar in all pages + during the loading screen
please assign this issue to me under gssoc'24

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Vidhi154** [comment]
please  assign this to me as I'm a gssoc contributor 
i have a good knowledge of web development.

**Comment by Agarwalvidu** [comment]
Go ahead @Jasleen1210 !

**Comment by d4jain** [comment]
Kindly assign this to me 
I have done this in a project made by in past 
You can check my projects in my profile

**Comment by Agarwalvidu** [comment]
@d4jain It is already assigned to other contributor I can't assign it to you. Hope you understand!
