### ISSUE TITLE
[DOCS] : Adding a Installation and Setup Guide.

### ISSUE THREAD

**Issue by iamkanhaiyakumar** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#29]
I've noticed your project lacks a Installation and Setup Guide, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully.
I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.

I've done a readme file for another project, you can check my profile, i always give my best.

Can you assign me this task?

Thank u @Muskansahuincredible

**Comment by Muskansahuincredible** [comment]
@iamkanhaiyakumar assigned

**Comment by iamkanhaiyakumar** [comment]
@Muskansahuincredible Can you open the Pr again Because did not get any point for this Merge , I will raised PR merged request again.

**Comment by iamkanhaiyakumar** [comment]
@Muskansahuincredible can you close the issue.
