### ISSUE TITLE
Enhancement: Rate us page

### ISSUE THREAD

**Issue by Jasleen1210** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#291]
### Description

I would like to edit and enhance the UI of the Rate us page 

>Add the blue background to match the website (currently gray) 
>Add text "Please leave a review"  (currently blank)
>Add more fields (name and email) 
>Enhancing submit button
>Adding footer to the page 

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Go ahead!
