### ISSUE TITLE
Review Section

### ISSUE THREAD

**Issue by Jasleen1210** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#293]
### Description

![image](https://github.com/user-attachments/assets/fbfd6cf0-1258-436c-a1da-c684584bdc9b)

I would like to add better styles to this review section (bottom of contact us page) [margins, border rounding, hover styles] and also ensure better view in mobile mode

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Go ahead!
