### ISSUE TITLE
Bug: Login Page: Mobile view

### ISSUE THREAD

**Issue by Jasleen1210** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#294]
### Description

In mobile view, the login page is not responsive. User is unable to scroll horizontally past the screen height hence hindering the login procedure.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Go ahead!
