### ISSUE TITLE
💡[FEATURE] Add FAQ section

### ISSUE THREAD

**Issue by komal-agarwal5** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#296]
### Description

I want to add an FAQ section with accordions
It will contain the frequently asked questions and help to solve query of users

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Hey I am closing this issue, as this is already been added in the project. Actually the deployed link is old. Please check the website after cloning, it is there.
