### ISSUE TITLE
💡[FEATURE] Design Blog Home Page

### ISSUE THREAD

**Issue by komal-agarwal5** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#297]
### Description

I want to design a blog home page which will have cards with images,title description
When blog data is available it can be put in these cards

### Screenshots

![Screenshot 2024-07-21 023430](https://github.com/user-attachments/assets/5012c0c0-15fa-47da-8bb3-77fa0434661e)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Hey I am closing this issue, as this is already been added in the project. Actually the deployed link is old. Please check the website after cloning, it is there.
