### ISSUE TITLE
💡[FEATURE] Make Terms and Conditions Page

### ISSUE THREAD

**Issue by komal-agarwal5** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#298]
### Description

I want to design and write a terms and conditions page

### Screenshots

![Screenshot 2024-07-21 023447](https://github.com/user-attachments/assets/6f4141bd-8c91-4d6f-a693-de020b435655)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Go ahead!

**Comment by Agarwalvidu** [comment]
Hey I am closing this issue, as this is already been added in the project. Actually the deployed link is old. Please check the website after cloning, it is there.
