### ISSUE TITLE
💡[FEATURE] Make Privacy Policy Page

### ISSUE THREAD

**Issue by komal-agarwal5** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#299]
### Description

I want to chalk down a privacy policy page for better usage

### Screenshots

![Screenshot 2024-07-21 023501](https://github.com/user-attachments/assets/d1156f2a-0454-4de7-9f68-46a14d039e80)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Go ahead!

**Comment by Agarwalvidu** [comment]
Hey I am closing this issue, as this is already been added in the project. Actually the deployed link is old. Please check the website after cloning, it is there.
