### ISSUE TITLE
Readme.md Update Required

### ISSUE THREAD

**Issue by Meetjain1** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#32]
Currently Our readme.md file is not looking good 
It is looking like a learn.md file I would suggest to @Muskansahuincredible @techmannih  assign me this issue I will create a fully new version of readme file , have created the same in many repository , I am working under gssoc

changes required are missing video of our project , allignment of text , open source section , contributors section , code of conduct, license section , features section and many more I will create a beautiful attracting readme file .

**Comment by Iamkg11** [comment]
I'd like to improve the clarity and conciseness of our README.md file. It currently reads more like a learning resource than a project introduction.

 I'm confident I can create a new version that effectively introduces our project and its functionalities.

Would @Muskansahuincredible or @techmannih be open to assigning this task to me?

**Comment by iamkanhaiyakumar** [comment]
I'd like to improve the clarity and conciseness of our README.md file. It currently reads more like a learning resource than a project introduction.
Thank you @Muskansahuincredible
