### ISSUE TITLE
Footer icons not working

### ISSUE THREAD

**Issue by kekubhai** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#320]
### What is your issue or question?

The app icons such as google twitter are not working on a click. The hover effect is also not presnet as per requiremnet.  These icons are not working on mobile, and not redirecting the user to the desired links.

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contribution Guidelines.
- [X] I have read the Code Of Conduct.
- [X] The changes don't break the code.

**Comment by dhananjay6561** [comment]
@kekubhai it is fixed. you mmay close the issue now.
