### ISSUE TITLE
unaligned buttons in nav in mobile view

### ISSUE THREAD

**Issue by Jasleen1210** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#325]
### Description

In mobile mode the login and sign up buttons are of different sizes

### Screenshots

![image](https://github.com/user-attachments/assets/e4cd73ea-3c0f-40b8-b69d-2275f7e489c1)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Go ahead!
