### ISSUE TITLE
Bug: Mobile view

### ISSUE THREAD

**Issue by Jasleen1210** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#327]
### Description

Unnecessary space in mobile mode between two containers 

### Screenshots

<img width="127" alt="image" src="https://github.com/user-attachments/assets/5d41e61b-b9d5-423a-b868-80f42955752a">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Go ahead!
