### ISSUE TITLE
Fix grammatical errors and enhance the contact links on the 'Contact Us' page

### ISSUE THREAD

**Issue by Anni299** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#328]
### Description

1) Fix Grammatical Errors: 
    - It should be 'Got "an" Idea' instead of 'Got "a" Idea'.
    - It should be 'Chat "With" Us' instead of 'Chat "On" Us'.
    
2) Enhance the contact links:
    - Clicking on the phone number and email id should redirect to 'calling' and 'mailto'.

### Screenshots

![image](https://github.com/user-attachments/assets/56830306-5ec5-484a-94ae-06d8963209cb)
![image](https://github.com/user-attachments/assets/f2d4efc5-cf24-4bd3-a32a-716998d06708)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Go ahead!
