### ISSUE TITLE
Footer on project page

### ISSUE THREAD

**Issue by Jasleen1210** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#334]
### Description

![image](https://github.com/user-attachments/assets/76e9e724-45c9-4cf0-bbb7-3f588d9246be)
Footer on that page has an unnecessary margin and padding unlike the rest of the pages 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Go ahead!
