### ISSUE TITLE
Enhance Feedback form

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#349]
### What is your issue or question?

I would like to improve the feedback form.

![Screenshot 2024-07-26 183750](https://github.com/user-attachments/assets/14ce0e04-cf4a-47c9-b664-2e1cd3af27c2)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contribution Guidelines.
- [X] I have read the Code Of Conduct.
- [X] The changes don't break the code.

**Comment by Agarwalvidu** [comment]
Go ahead!
