### ISSUE TITLE
White Space in the footer

### ISSUE THREAD

**Issue by dhananjay6561** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#359]
### Description

The footer is not stretched completely to the bottom of the page.

### Screenshots

![image](https://github.com/user-attachments/assets/406ba813-c7af-4a45-9608-9cb3ef378934)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by Agarwalvidu** [comment]
Go ahead!
