### ISSUE TITLE
💡Adding a Animated Cursor

### ISSUE THREAD

**Issue by PratikMane0112** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#366]
### Description

I will add a animated cursor which will fit to website color scheme & UI.

### Screenshots

![rgb](https://github.com/user-attachments/assets/d6e4a347-6e91-4466-a571-319ca32e21e4)

I will add any if the above animated cursor which will fit to website color scheme & UI.

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by zzzzshawn** [comment]
i would also like to be assigned this task
