### ISSUE TITLE
BUG REPORT: Mobile navbar

### ISSUE THREAD

**Issue by zzzzshawn** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#371]
### Description

Navbar on mobile wont open even after clicking the navbar button

### Screenshots

![Screenshot (64)](https://github.com/user-attachments/assets/6db1c828-1924-48f1-a84a-8f6ed8a399eb)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by dhananjay6561** [comment]
@zzzzshawn As per the latest code , the navbar is working and responsive in mobile view so you may close the issue.
