### ISSUE TITLE
📝[DOCS] <Grammar Issues Contact Us page>

### ISSUE THREAD

**Issue by quarfora** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#401]
### Issue Description

The following should be changed to:

> **Got an idea? We've got the skills. Let's team up.
> Tell us more about yourself and what you've got in mind.**

OR If a more formal/professional tone is desired:

> **Have an idea? We have the skills. Let's team up.
> Tell us more about yourself and what you have in mind.**

Explanation:
- a is the wrong article and should be an due to the next word, idea, starting with a vowel.
- The "i" in idea should not be capitalized.
- A period is needed after up.
- you're means "you are" should be switched to the contraction you've for "you have".

"Chat on us" should be changed to "Chat with us" to make it more clear to users.

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/fc5c1c93-fb5a-489d-8b37-672a4887507d)
![image](https://github.com/user-attachments/assets/27c7b64f-6791-4fb7-b9b0-476e7a8adcd6)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines.
- [X] I have read the Code Of Conduct.
- [X] The changes doesn't break the code

**Comment by quarfora** [comment]
Please assign this to me when you get the chance.

**Comment by Agarwalvidu** [comment]
Please check after cloning, deployed one is not updated!
