### ISSUE TITLE
OTP authentication 

### ISSUE THREAD

**Issue by Muskansahuincredible** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#47]
![Screenshot_2024-05-23-03-32-28-72_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/113519369/854e160a-a068-4962-82ad-e063119f3ae0)
Change the page where the OTP is send directly to their mail id ..A bug is there in a website where  the OTP is not sent successfully and the OTP code is also not generated.

**Comment by shivamgaur99** [comment]
@Muskansahuincredible, i would like to work

**Comment by dikshagupta3094** [comment]
@Muskansahuincredible  , Please assign this issue to me I would I like to work on it

**Comment by shivamgaur99** [comment]
@techmannih, i have solved this issue but there are also bug in signup Could you please revise the levels?
