### ISSUE TITLE
Adding Favicon to website . 

### ISSUE THREAD

**Issue by PratikMane0112** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#5]
Favicon is missing for the website & it default as for react & tailwind css.

![Screenshot 2024-05-12 201245](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/153143167/63a22edf-80cb-45e4-a204-19c9e08474f4)

I will add appropriate favicon to website which will fit to overall website & enhance a self identity for browser tabs.

**Comment by Muskansahuincredible** [comment]
@PratikMane0112 Assigned
