### ISSUE TITLE
Add Password Strength Validation to Signup Form

### ISSUE THREAD

**Issue by dadigavasavipriya** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#86]
### Description

The current signup form does not enforce strong password policies, potentially compromising account security. Password strength is a crucial aspect of online security, as weak passwords can be easily guessed or cracked by malicious actors, leading to unauthorized access to user accounts. To ensure robust security, the password field should enforce the following requirements:

-At least 8 characters long
-Contains at least one uppercase letter
-Contains at least one lowercase letter
-Contains at least one number
-Contains at least one special character

Implement a validation function that checks for the above requirements and displays an appropriate error message if the password does not meet the criteria. This enhancement will improve account security by ensuring users create strong passwords, thereby protecting their personal information and enhancing the overall security posture of the platform.

@Muskansahuincredible, please assign me this issue. As an GSSoc Contributor I am eager to contribute to enhancing the security of our platform by implementing strong password validation in the signup form.

### What browser are you seeing this bug on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by dadigavasavipriya** [comment]
@Muskansahuincredible thank you for assigning me this issue.I am glad to contribute to this project.Can you please  label level to this issue.

**Comment by lassmara** [comment]
Please assign me this issue.

**Comment by Shanmukha18** [comment]
please assign this issue to me

**Comment by dadigavasavipriya** [comment]
@Muskansahuincredible  I wanted to inform you that I have created the pull request for this issue. Please review it and let me know if you have any questions or need further changes. Here’s the link to the PR: [https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/pull/113#issue-2323334586] . Thank you for your patience.

**Comment by dadigavasavipriya** [comment]
Thank you @Muskansahuincredible. I am glad to contribute to this project.
