### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by anshika-gupta21** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#87]
### What is your issue or question?

Hello @Muskansahuincredible, I would like to add hover effect on Log In and Sign Up buttons on Navbar. It would enhance the look of the website even more. Kindly assign me this issue.

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contribution Guidelines.
- [X] I have read the Code Of Conduct.
- [X] The changes don't break the code.

**Comment by techmannih** [comment]
sorry no need of this now. so, I closing this issue please work on another issue
