### ISSUE TITLE
💡[FEATURE] Implement hover effect for login button to improve user experience

### ISSUE THREAD

**Issue by hetvipopat** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#98]
### Description

Currently, there is not any visual indication when a user hovers button.
kindly assign this issue to me under GSSOC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the StudyNotion-An-Online-Education-Platform. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by Muskansahuincredible** [comment]
@hetvipopat assigned
